services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ais
      POSTGRES_PASSWORD: ais
      POSTGRES_DB: ais
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8081"]
volumes:
  pgdata: {}
