server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ais   # ak máš DB na 5433, zmeň na 5433
    username: ais
    password: ais
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update         # nech to prvýkrát vytvorí tabuľky
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true             # dočasne vypnuté, zapneme neskôr

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO

security:
  jwt:
    secret: q2y5l0s8v1x4n7r3q5n0z8v2x1l4k7r9  # zmeň na reálne tajomstvo
    issuer: ais-api
    expiration: PT1H